controller_list:
  - name: fake_arm_controller
    joints:
      - motor1_to_base_turn_table
      - motor2_to_arm1
      - motor3_to_arm2
      - motor4_to_wrist
      - motor5_to_wrist_rotate
  - name: fake_hand_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: arm
    pose: start