# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - motor1_to_base_turn_table
    - motor2_to_arm1
    - motor3_to_arm2
    - motor4_to_wrist
    - motor5_to_wrist_rotate
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - motor1_to_base_turn_table
    - motor2_to_arm1
    - motor3_to_arm2
    - motor4_to_wrist
    - motor5_to_wrist_rotate
  gains:
    motor1_to_base_turn_table:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor2_to_arm1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor3_to_arm2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor4_to_wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    motor5_to_wrist_rotate:
      p: 100
      d: 1
      i: 1
      i_clamp: 1